### ISSUE TITLE
Chaining promises in version 7+

### ISSUE THREAD

**Issue by danamajid** [then/promise#93] opened 2015-04-30 11:05 UTC
I'm trying to just do a simple chaining of promises, by first pushing promises to an array and then do `Promise.all(array).then(function(results) { console.log(results); })`. This used to work just fine in v6.x, but since upgrading to the latest version, it fails.

At the essence, what seems to differ from before is:

```
console.log(new Promise(function (resolve, reject) {
  resolve();
}));
```
Previously this would log: `{ then: [Function] }`

Now on version 7.0.1, this results in: `{ _32: 0, _8: null, _89: [] }`

Did I miss a change in API or am I messing things up? :)

**Comment by samuelbeek** [comment] 2015-04-30 11:20
+1

**Comment by kayvink** [comment] 2015-04-30 11:20
+1

**Comment by ForbesLindesay** [comment] 2015-04-30 12:28
`then` is now on the prototype.  What this means is that you can no longer do:

```js
var promise = new Promise(function (resolve) {
  resolve();
});
var then = promise.then;
then(function () {}); // this won't work
promise.then(function () {}); // but this would work fine
```

If you can produce an example of code that fails, I'd be very happy to look into why it fails.

**Comment by danamajid** [comment] 2015-04-30 12:56
Thanks, that did the trick.

For future readers: in order to do `Promise.all(promisesArray)`, the `promisesArray` should look like: `[promiseA.then(), promiseB.then()]` and not `[promiseA, promiseB]` like before.

**Comment by ForbesLindesay** [comment] 2015-04-30 12:58
no, there should be no need to do that.

**Comment by ForbesLindesay** [comment] 2015-04-30 12:59
If you could provide an example that demonstrates the failure, it would be incredibly helpful.

**Comment by ForbesLindesay** [comment] 2015-04-30 13:07
Could you tell me what exactly the failure is when you do `Promise.all(array).then(function(results) { console.log(results); })`?  Do you get an exception?  Does it just never resolve?

**Comment by danamajid** [comment] 2015-04-30 13:11
It just never resolves. Just wrote a reduced version but that works like you said – so something else must be causing it.. So I am separating things now to find out. Stay tuned.

**Comment by ForbesLindesay** [comment] 2015-04-30 13:15
Are you interacting with any other promise libraries?  Especially libraries like lazy-promise (which inherit from promise as a base class)?

**Comment by danamajid** [comment] 2015-04-30 13:21
No. Only thing out of the ordinary is that its populating the array inside `multiparty`'s `form.on('part')`.

Can't reproduce a test case right now and have to run. Either way, think it's unrelated to this lib. Feel free to close the issue.

**Comment by ForbesLindesay** [comment] 2015-04-30 13:38
OK, please post here when you manage to produce a test case.  @samuelbeek & @kayvink perhaps one of you can produce an example?

If all the promises were Promises/A+ compliant, then there is a bug in this library so I'd very much like to get to the bottom of it.

**Comment by samuelbeek** [comment] 2015-05-01 08:25
@ForbesLindesay unfortunately @danamajid fixed the problem for me too (since we work together).

**Comment by ForbesLindesay** [comment] 2015-06-15 11:02
It turns out this is (see #99) caused by asap sometimes calling back twice and sometimes not at all.  The offending issue is https://github.com/kriskowal/asap/issues/55, which has now been resolved.  Updating asap should be sufficient, which should happen automatically if you delete any caches and re-install.

I will release an update of promise that requires the latest version of asap though to encourage people to update faster.

**Comment by nathan7** [comment] 2015-08-02 04:34
Closing this, given that `promise@7.0.3` resolves this.

**Closed by nathan7** 2015-08-02 04:34 UTC
